# Generated by Django 5.2.5 on 2025-09-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('user_id', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
            ],
        ),
    ]
